---

name:
    solana-staking-csvs
version:
    0.1.0.0
github:
    prikhi/solana-staking-csvs
homepage:
    https://github.com/prikhi/solana-staking-csv#readme
license:
    BSD3
license-file:
    LICENSE
author:
    Pavan Rikhi
maintainer:
    pavan.rikhi@gmail.com
copyright:
    2021 Pavan Rikhi
category:
    Web, Finance, Console
extra-source-files:
    - README.md
    - CHANGELOG.md


synopsis:
    Generate CSV Exports of your Solana Staking Rewards.

description: |
    @solana-staking-csvs@ is a CLI program that queries the Solana blockchain
    for an account's staking accounts, and exports all their staking rewards to
    a CSV file.

    The <https://solanabeach.io/ Solana Beach API> is used to fetch data from
    the blockchain and you will need a <https://github.com/solana-beach/api
    free API key> to use this program.

    You can install @solana-stakingc-csvs@ with Stack: @stack install --resolver
    nightly solana-staking-csvs@. Then run @solana-staking-csvs <API_KEY>
    <ACCOUNT_PUBKEY>@ to print out your rewards in CSV format.


ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -O2


dependencies:
    - base >= 4.7 && < 5

default-extensions:
    - DataKinds
    - DeriveGeneric
    - LambdaCase
    - OverloadedStrings
    - TupleSections
    - TypeApplications
    - ViewPatterns


library:
    source-dirs:
        src
    dependencies:
        - aeson >= 1 && < 2
        - mtl >= 2 && < 3
        - req >= 3 && < 4
        - scientific < 1
        - text < 2
        - time < 2

executables:
    solana-staking-csvs:
        source-dirs:
            app
        main:
            Main.hs
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - solana-staking-csvs

tests:
    solana-staking-csvs-test:
        main: Spec.hs
        source-dirs:
            tests
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - solana-staking-csvs
            - hedgehog
            - tasty
            - tasty-hedgehog
            - tasty-hunit
